---
name: cd

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
    - name: Install Goose
      run: go install github.com/pressly/goose/v3/cmd/goose@latest
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Build notely
      run: scripts/buildprod.sh
    - name: Build and push Docker image to Google Artifact Registry
      run: gcloud builds submit --tag europe-west2-docker.pkg.dev/notely-438006/notely-ar-repo/notely:latest .
    - name: Run database migrations
      run: scripts/migrateup.sh
    - name: Deploy to Cloud Run
      run: gcloud run deploy notely --image europe-west2-docker.pkg.dev/notely-438006/notely-ar-repo/notely:latest --region europe-west2 --allow-unauthenticated --project notely-438006 --max-instances=2
